/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simsen_simapi_TestNative */

#ifndef _Included_simsen_simapi_TestNative
#define _Included_simsen_simapi_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simsen_simapi_TestNative
 * Method:    drawCircleShape
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_simsen_simapi_TestNative_drawCircleShape
  (JNIEnv *, jobject);

/*
 * Class:     simsen_simapi_TestNative
 * Method:    drawEightShape
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_simsen_simapi_TestNative_drawEightShape
  (JNIEnv *, jobject);

/*
 * Class:     simsen_simapi_TestNative
 * Method:    drawGroundShape
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_simsen_simapi_TestNative_drawGroundShape
  (JNIEnv *, jobject);

/*
 * Class:     simsen_simapi_TestNative
 * Method:    movePointer
 * Signature: (DDDDZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_simsen_simapi_TestNative_movePointer
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
